[build-system]
requires = ["setuptools", "wheel", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "pyPDAF"
authors = [
    {name = "Yumeng Chen", email = "yumeng.chen@reading.ac.uk"},
]
version = "1.0.0"
description = "A Python interface to Parallel Data Assimilation Framework (PDAF)"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["data assimilation", "PDAF"]
license = {text = "GPL License"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy", "mpi4py"
]

