"""docstrings for PDAF_assimilate functions

These functions are mostly deprecated.
"""
docstrings = dict()


docstrings['assimilate_3dvar'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_3dvar`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_3dvar_nondiagR`.\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "3DVar DA for a single step without OMI.\n    " \
    "When 3DVar is used, the background error covariance matrix"\
    "\n    has to be modelled for cotrol variable\n    " \
    "transformation. This is a deterministic filtering\n    " \
    "scheme so no ensemble and\n    " \
    "parallelisation is needed.\n    " \
    "This function should be called at each model time step.\n" \
    "\n    The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_3dvar`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    "\
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf\n    " \
    "    5. py__init_obs_pdaf\n    " \
    "    6. Iterative optimisation:\n    " \
    "        1. py__cvt_pdaf\n    " \
    "        2. py__obs_op_lin_pdaf\n    " \
    "        3. py__prodRinvA_pdaf\n    " \
    "        4. py__obs_op_adj_pdaf\n    " \
    "        5. py__cvt_adj_pdaf\n    " \
    "        6. core DA algorithm\n    " \
    "    7. py__cvt_pdaf\n    " \
    "    8. py__prepoststep_state_pdaf\n    " \
    "    9. py__distribute_state_pdaf\n    " \
    "    10. py__next_observation_pdaf\n\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by :func:`pyPDAF.PDAF.omi_assimilate_3dvar`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_3dvar_nondiagR`"
docstrings['assimilate_en3dvar_estkf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_en3dvar_estkf`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_en3dvar_estkf_nondiagR`." \
    "\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "3DEnVar for a single DA step.\n    " \
    "The background error covariance matrix is estimated\n    " \
    "by an ensemble.\n    " \
    "The 3DEnVar only calculates the analysis of the ensemble mean." \
    "\n    " \
    "An ESTKF is used along with 3DEnVar\n    " \
    "to generate ensemble perturbations.\n    " \
    "This function should be called at each model time step.\n" \
    "\n    The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_en3dvar_estkf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf\n    " \
    "    5. py__init_obs_pdaf\n    " \
    "    6. the iterative optimisation:\n    " \
    "        1. py__cvt_ens_pdaf\n    " \
    "        2. py__obs_op_lin_pdaf\n    " \
    "        3. py__prodRinvA_pdaf\n    " \
    "        4. py__obs_op_adj_pdaf\n    " \
    "        5. py__cvt_adj_ens_pdaf\n    " \
    "        6. core 3DEnVar algorithm\n    " \
    "    7. py__cvt_ens_pdaf\n    " \
    "    8. ESTKF:\n    " \
    "        1. py__init_dim_obs_pdaf\n    " \
    "        2. py__obs_op_pdaf (for ensemble mean)\n    " \
    "        3. py__init_obs_pdaf\n    " \
    "        4. py__obs_op_pdaf (for each ensemble member)\n    " \
    "        5. py__init_obsvar_pdaf\n    " \
    "           (only relevant for adaptive\n    " \
    "           forgetting factor schemes)\n    " \
    "        6. py__prodRinvA_pdaf\n    " \
    "        7. core ESTKF algorithm\n    " \
    "    9. py__prepoststep_state_pdaf\n    " \
    "    10. py__distribute_state_pdaf\n    " \
    "    11. py__next_observation_pdaf\n\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_en3dvar_estkf`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_en3dvar_estkf_nondiagR`"
docstrings['assimilate_en3dvar_lestkf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.localomi_assimilate_en3dvar_lestkf` or" \
    "\n    " \
    ":func:`pyPDAF.PDAF.localomi_assimilate_en3dvar_lestkf_nondiagR`."\
    "\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "3DEnVar for a single DA step where the ensemble anomaly\n    " \
    "is generated by LESTKF.\n    " \
    "The background error covariance matrix is\n    " \
    "estimated by ensemble.\n    " \
    "The 3DEnVar only calculates the analysis of the ensemble mean." \
    "\n    " \
    "An LESTKF is used to generate ensemble perturbations.\n    " \
    "This function should be called at each model time step.\n" \
    "\n    " \
    "The function is a combination of" \
    "\n    " \
    ":func:`pyPDAF.PDAF.put_state_en3dvar_lestkf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf\n    " \
    "    5. py__init_obs_pdaf\n    " \
    "    6. Starting the iterative optimisation:\n    " \
    "        1. py__cvt_ens_pdaf\n    " \
    "        2. py__obs_op_lin_pdaf\n    " \
    "        3. py__prodRinvA_pdaf\n    " \
    "        4. py__obs_op_adj_pdaf\n    " \
    "        5. py__cvt_adj_ens_pdaf\n    " \
    "        6. core DA algorithm\n    " \
    "    7. py__cvt_ens_pdaf\n    " \
    "    8. Perform LESTKF:\n    " \
    "        1. py__init_n_domains_p_pdaf\n    " \
    "        2. py__init_dim_obs_pdaf\n    " \
    "        3. py__obs_op_pdaf\n    "\
    "           (for each ensemble member)\n    " \
    "        4. py__init_obs_pdaf\n    "\
    "           (if global adaptive forgetting factor is used\n    " \
    "           `type_forget=1` in :func:`pyPDAF.PDAF.init`)\n    " \
    "        5. py__init_obsvar_pdaf\n    "\
    "           (if global adaptive forgetting factor is used)" \
    "\n    " \
    "        6. loop over each local domain:\n    " \
    "            1. py__init_dim_l_pdaf\n    " \
    "            2. py__init_dim_obs_l_pdaf\n    " \
    "            3. py__g2l_state_pdaf\n    " \
    "            4. py__g2l_obs_pdaf\n    "\
    "               (localise mean ensemble in observation space)"\
    "\n    " \
    "            5. py__init_obs_l_pdaf\n    "\
    "            6. py__g2l_obs_pdaf\n    " \
    "               (localise each ensemble member\n    " \
    "               in observation space)\n    " \
    "            7. py__init_obsvar_l_pdaf\n    " \
    "               (only called if local\n    " \
    "               adaptive forgetting factor\n    " \
    "               `type_forget=2` is used)\n    "\
    "            8. py__prodRinvA_l_pdaf\n    " \
    "            9. core DA algorithm\n    " \
    "            10. py__l2g_state_pdaf\n    " \
    "    9. py__prepoststep_state_pdaf\n    " \
    "    10. py__distribute_state_pdaf\n    " \
    "    11. py__next_observation_pdaf\n\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.localomi_assimilate_en3dvar_lestkf`" \
    "\n    " \
    "   and\n    " \
    "   :func:`pyPDAF.PDAF.localomi_assimilate_en3dvar_lestkf_nondiagR`"
docstrings['assimilate_hyb3dvar_estkf'] = \
    "It is recommended to use" \
    "\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_hyb3dvar_estkf`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_hyb3dvar_estkf_nondiagR`." \
    "\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions" \
    "\n    " \
    "and improved efficiency.\n\n    " \
    "Hybrid 3DEnVar for a single DA step where\n    " \
    "the background error covariance is hybridised by" \
    "\n    " \
    "a static background error covariance,\n    " \
    "and a flow-dependent background error covariance" \
    "\n    " \
    "estimated from ensemble.\n    " \
    "The 3DVar generates an ensemble mean and" \
    "\n    " \
    "the ensemble perturbation is generated by\n    " \
    "ESTKF in this implementation.\n    " \
    "This function should be called at each model time step.\n\n    " \
    "The function is a combination of" \
    "\n    " \
    ":func:`pyPDAF.PDAF.put_state_hyb3dvar_estkf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf\n    " \
    "    5. py__init_obs_pdaf\n    " \
    "    6. the iterative optimisation:\n    " \
    "        1. py__cvt_pdaf\n    " \
    "        2. py__cvt_ens_pdaf\n    " \
    "        3. py__obs_op_lin_pdaf\n    " \
    "        4. py__prodRinvA_pdaf\n    " \
    "        5. py__obs_op_adj_pdaf\n    " \
    "        6. py__cvt_adj_pdaf\n    " \
    "        7. py__cvt_adj_ens_pdaf\n    " \
    "        8. core 3DEnVar algorithm\n    " \
    "    7. py__cvt_pdaf\n    " \
    "    8. py__cvt_ens_pdaf\n    " \
    "    9. Perform ESTKF:\n    " \
    "        1. py__init_dim_obs_pdaf\n    " \
    "        2. py__obs_op_pdaf\n    "\
    "           (for ensemble mean)\n    " \
    "        3. py__init_obs_pdaf\n    " \
    "        4. py__obs_op_pdaf\n    " \
    "           (for each ensemble member)\n    " \
    "        5. py__init_obsvar_pdaf\n    " \
    "           (only relevant for adaptive" \
    "\n    " \
    "           forgetting factor schemes)\n    " \
    "        6. py__prodRinvA_pdaf\n    " \
    "        7. core ESTKF algorithm\n    " \
    "    10. py__prepoststep_state_pdaf\n    " \
    "    11. py__distribute_state_pdaf\n    " \
    "    12. py__next_observation_pdaf\n\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by" \
    "\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_hyb3dvar_estkf` and" \
    "\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_hyb3dvar_estkf_nondiagR`."
docstrings['assimilate_hyb3dvar_lestkf'] = \
    "It is recommended to use" \
    "\n    " \
    ":func:`pyPDAF.PDAF.localomi_assimilate_hyb3dvar_lestkf` or" \
    "\n    "\
    ":func:`pyPDAF.PDAF.localomi_assimilate_hyb3dvar_lestkf_nondiagR`." \
    "\n\n    " \
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "Hybrid 3DEnVar for a single DA step where\n    " \
    "the background error covariance is hybridised by\n    " \
    "a static background error covariance,\n    " \
    "and a flow-dependent background error covariance\n    " \
    "estimated from ensemble.\n    " \
    "The 3DVar generates an ensemble mean and\n    " \
    "the ensemble perturbation is generated by\n    " \
    "LESTKF in this implementation.\n    " \
    "This function should be called at each model time step.\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_hyb3dvar_lestkf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf\n    " \
    "    5. py__init_obs_pdaf\n    " \
    "    6. The iterative optimisation:\n    " \
    "        1. py__cvt_pdaf\n    " \
    "        2. py__cvt_ens_pdaf\n    " \
    "        3. py__obs_op_lin_pdaf\n    " \
    "        4. py__prodRinvA_pdaf\n    " \
    "        5. py__obs_op_adj_pdaf\n    " \
    "        6. py__cvt_adj_pdaf\n    " \
    "        7. py__cvt_adj_ens_pdaf\n    " \
    "        8. core DA algorithm\n    " \
    "    7. py__cvt_pdaf\n    " \
    "    8. py__cvt_ens_pdaf\n    " \
    "    9. Perform LESTKF:\n    " \
    "        1. py__init_n_domains_p_pdaf\n    " \
    "        2. py__init_dim_obs_pdaf\n    " \
    "        3. py__obs_op_pdaf\n    " \
    "           (for each ensemble member)\n    " \
    "        4. py__init_obs_pdaf\n    " \
    "           (if global adaptive forgetting factor\n    " \
    "           `type_forget=1` in :func:`pyPDAF.PDAF.init`)\n    " \
    "        5. py__init_obsvar_pdaf\n    " \
    "           (if global adaptive forgetting factor is used)\n    " \
    "        6. loop over each local domain:\n    " \
    "            1. py__init_dim_l_pdaf\n    " \
    "            2. py__init_dim_obs_l_pdaf\n    " \
    "            3. py__g2l_state_pdaf\n    " \
    "            4. py__g2l_obs_pdaf\n    "\
    "               (localise mean ensemble in observation space)" \
    "\n    " \
    "            5. py__init_obs_l_pdaf\n    "\
    "            6. py__g2l_obs_pdaf\n    " \
    "               (localise each ensemble member\n    " \
    "               in observation space)\n    " \
    "            7. py__init_obsvar_l_pdaf\n    " \
    "               (only called if local adaptive forgetting\n    " \
    "               factor `type_forget=2` is used)\n    "\
    "            8. py__prodRinvA_l_pdaf\n    " \
    "            9. core DA algorithm\n    " \
    "            10. py__l2g_state_pdaf\n    " \
    "    10. py__prepoststep_state_pdaf\n    " \
    "    11. py__distribute_state_pdaf\n    " \
    "    12. py__next_observation_pdaf\n\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.localomi_assimilate_hyb3dvar_lestkf`" \
    "\n    " \
    "   and\n    " \
    "   :func:`pyPDAF.PDAF.localomi_assimilate_hyb3dvar_lestkf_nondiagR`"
docstrings['assimilate_enkf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_global`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_enkf_nondiagR`.\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "Stochastic EnKF (ensemble " \
    "Kalman filter) [1]_ for a single DA step without OMI.\n    " \
    "This function should be called at each model time step. \n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_enkf` " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf (for ensemble mean)\n    " \
    "    5. py__add_obs_err_pdaf\n    " \
    "    6. py__init_obs_pdaf\n    " \
    "    7. py__init_obscovar_pdaf\n    " \
    "    8. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    9. core DA algorithm\n    " \
    "    10. py__prepoststep_state_pdaf\n    " \
    "    11. py__distribute_state_pdaf\n    " \
    "    12. py__next_observation_pdaf\n\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_global`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_enkf_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Evensen, G. (1994), \n    "\
    "       Sequential data assimilation with a nonlinear\n    " \
    "       quasi-geostrophic model\n    "\
    "       using Monte Carlo methods to forecast error statistics," \
    "\n    "\
    "       J. Geophys. Res., 99(C5), 10143–10162,\n    " \
    "       doi:10.1029/94JC00572."
docstrings['assimilate_estkf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_global`\n    " \
    "or :func:`pyPDAF.PDAF.omi_assimilate_global_nondiagR`\n    " \
    "instead of this function.\n\n    " \
    "OMI functions need fewer user-supplied functions\n    " \
    "and improve DA efficiency.\n\n    " \
    "This function calls ESTKF\n    " \
    "(error space transform Kalman filter) [1]_.\n    " \
    "The ESTKF is a more efficient equivalent to the ETKF.\n\n    " \
    "The function should be called at each model time step.\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_estkf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf (for ensemble mean)\n    " \
    "    5. py__init_obs_pdaf\n    " \
    "    6. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    7. py__init_obsvar_pdaf (only relevant\n    " \
    "       for adaptive forgetting factor schemes)\n    " \
    "    8. py__prodRinvA_pdaf\n    " \
    "    9. core DA algorithm\n    " \
    "    10. py__prepoststep_state_pdaf\n    " \
    "    11. py__distribute_state_pdaf\n    " \
    "    12. py__next_observation_pdaf\n\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_global`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_global_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Nerger, L., Janjić, T., Schröter, J., Hiller, W. (2012)."\
    "\n    " \
    "       A unification of ensemble square root Kalman filters." \
    "\n    " \
    "       Monthly Weather Review, 140, 2335-2345.\n    " \
    "       doi:10.1175/MWR-D-11-00102.1"
docstrings['assimilate_etkf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_global`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_global_nondiagR`.\n\n    "\
    "PDAFlocal-OMI modules require fewer\n    " \
    "user-supplied functions and improved efficiency.\n\n    " \
    "Using ETKF (ensemble transform\n    " \
    "Kalman filter) [1]_ for a single DA step without OMI.\n    " \
    "The implementation is baed on [2]_.\n\n    " \
    "This function should be called at each model time step.\n    " \
    "The function is a combination of \n    " \
    ":func:`pyPDAF.PDAF.put_state_etkf` " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf (for ensemble mean)\n    " \
    "    5. py__init_obs_pdaf\n    " \
    "    6. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    7. py__init_obsvar_pdaf (only relevant for\n    " \
    "       adaptive forgetting factor schemes)\n    " \
    "    8. py__prodRinvA_pdaf\n    " \
    "    9. core DA algorithm\n    " \
    "    10. py__prepoststep_state_pdaf\n    " \
    "    11. py__distribute_state_pdaf\n    " \
    "    12. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_global`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_global_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Bishop, C. H., B. J. Etherton, and S. J. Majumdar (2001)" \
    "\n    "\
    "       Adaptive Sampling with the Ensemble\n    " \
    "       Transform Kalman Filter.\n    " \
    "       Part I: Theoretical Aspects. Mon. Wea. Rev.,\n    " \
    "       129, 420–436,\n    "\
    "       doi: 10.1175/1520-0493(2001)129<0420:ASWTET>2.0.CO;2." \
    "\n    " \
    ".. [2] Nerger, L., Janjić, T., Schröter, J., Hiller, W. (2012)." \
    "\n    " \
    "       A unification of ensemble square root Kalman filters." \
    "\n    " \
    "       Monthly Weather Review, 140, 2335-2345.\n    " \
    "       doi:10.1175/MWR-D-11-00102.1"
docstrings['assimilate_seek'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_global`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_global_nondiagR`.\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "This function will use singular evolutive\n    " \
    "extended Kalman filter [1]_ for a single DA step.\n    " \
    "This is a deterministic Kalman filter.\n    " \
    "The function should be called at each model step.\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_seek`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    "\
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf (for ensemble mean)\n    " \
    "    5. py__init_obs_pdaf\n    " \
    "    6. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    7. py__prodRinvA_pdaf\n    " \
    "    8. core DA algorithm\n    " \
    "    9. py__prepoststep_state_pdaf\n    " \
    "    10. py__distribute_state_pdaf\n    " \
    "    11. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_global`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_global_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Pham, D. T., Verron, J., & Roubaud, M. C. (1998).\n    "\
    "       A singular evolutive extended Kalman filter\n    " \
    "       for data assimilation\n    "\
    "       in oceanography. Journal of Marine systems,\n    " \
    "       16(3-4), 323-340."
docstrings['assimilate_seik'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_global`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_global_nondiagR`.\n\n    " \
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "This function will use singular evolutive\n    " \
    "interpolated Kalman filter [1]_ for a single DA step.\n    " \
    "The function should be called at each model step.\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_seik`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    "\
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf (for ensemble mean)\n    " \
    "    5. py__init_obs_pdaf\n    " \
    "    6. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    7. py__init_obsvar_pdaf (only relevant for\n    " \
    "       adaptive forgetting factor schemes)\n    " \
    "    8. py__prodRinvA_pdaf\n    " \
    "    9. core DA algorithm\n    " \
    "    10. py__prepoststep_state_pdaf\n    " \
    "    11. py__distribute_state_pdaf\n    " \
    "    12. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_global`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_global_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Pham, D. T., Verron, J., & Roubaud, M. C. (1998).\n    "\
    "       A singular evolutive extended Kalman\n    " \
    "       filter for data assimilation\n    "\
    "       in oceanography. Journal of Marine systems,\n    " \
    "       16(3-4), 323-340."
docstrings['assimilate_netf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_global`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_nonlin_nondiagR`.\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "This function will use Nonlinear Ensemble\n    " \
    "Transform Filter (NETF) [1]_ \n    " \
    "for a single DA step. The nonlinear filter\n    " \
    "computes the distribution up to\n    " \
    "the second moment similar to KF but using\n    " \
    "a nonlinear weighting similar to\n    " \
    "particle filter. This leads to an equal\n    " \
    "weights assumption for prior ensemble.\n    " \
    "The function should be called at each model step.\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_netf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    "\
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__init_obs_pdaf\n    " \
    "    5. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    6. py__likelihood_pdaf\n    " \
    "    7. core DA algorithm\n    " \
    "    8. py__prepoststep_state_pdaf\n    " \
    "    9. py__distribute_state_pdaf\n    " \
    "    10. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_global`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_nonlin_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Tödter, J., and B. Ahrens, 2015:\n    "\
    "       A second-order exact ensemble square root filter\n    " \
    "       for nonlinear data assimilation. Mon. Wea. Rev.,\n    " \
    "       143, 1347–1367, doi:10.1175/MWR-D-14-00108.1."
docstrings['assimilate_pf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_global`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_nonlin_nondiagR`.\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "This function will use particle filter for a single DA step." \
    "\n    " \
    "This is a fully nonlinear filter, and may require\n    " \
    "a high number of ensemble members.\n    " \
    "A review of particle filter can be found at [1]_.\n    " \
    "The function should be called at each model step.\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_pf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    "\
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__init_obs_pdaf\n    " \
    "    5. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    6. py__likelihood_pdaf\n    " \
    "    7. core DA algorithm\n    " \
    "    8. py__prepoststep_state_pdaf\n    " \
    "    9. py__distribute_state_pdaf\n    " \
    "    10. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_global`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_nonlin_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Van Leeuwen, P. J., Künsch, H. R.,\n    " \
    "       Nerger, L., Potthast, R., & Reich, S. (2019).\n    "\
    "       Particle filters for high‐dimensional geoscience\n    " \
    "       applications:\n    "\
    "       A review. Quarterly Journal of the Royal\n    " \
    "       Meteorological Society, 145(723), 2335-2365."
docstrings['assimilate_lenkf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_assimilate_lenkf`\n    "\
    "or :func:`pyPDAF.PDAF.omi_assimilate_lenkf_nondiagR`.\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "Stochastic EnKF (ensemble Kalman filter)\n    " \
    "with covariance localisation [1]_\n    " \
    "for a single DA step without OMI.\n\n    " \
    "This is the only scheme for covariance localisation in PDAF." \
    "\n\n    " \
    "This function should be called at each model time step.\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_lenkf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    5. py__localize_pdaf\n    " \
    "    6. py__add_obs_err_pdaf\n    " \
    "    7. py__init_obs_pdaf\n    " \
    "    8. py__init_obscovar_pdaf\n    " \
    "    9. py__obs_op_pdaf (repeated to reduce storage)\n    " \
    "    10. core DA algorith\n    " \
    "    11. py__prepoststep_state_pdaf\n    " \
    "    12. py__distribute_state_pdaf\n    " \
    "    13. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.omi_assimilate_lenkf`\n    " \
    "   and :func:`pyPDAF.PDAF.omi_assimilate_lenkf_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Houtekamer, P. L., and H. L. Mitchell (1998): \n    " \
    "       Data Assimilation Using an Ensemble Kalman Filter\n    " \
    "       Technique.\n    "\
    "       Mon. Wea. Rev., 126, 796–811,\n    "\
    "       doi: 10.1175/1520-0493(1998)126<0796:DAUAEK>2.0.CO;2."
docstrings['assimilate_lestkf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.localomi_assimilate`\n    "\
    "or :func:`pyPDAF.PDAF.localomi_assimilate_nondiagR`.\n\n    "\
    "PDAFlocal-OMI modules require fewer user-supplied\n    " \
    "functions and improved efficiency.\n\n    " \
    "Local ESTKF (error space transform " \
    "Kalman filter) [1]_ for a single DA step without OMI.\n    " \
    "The LESTKF is a more efficient equivalent to the LETKF.\n\n    " \
    "This function should be called at each model time step.\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_lestkf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    "\
    "    2. py__prepoststep_state_pdaf\n    "\
    "    3. py__init_n_domains_p_pdaf\n    "\
    "    4. py__init_dim_obs_pdaf\n    "\
    "    5. py__obs_op_pdaf (for each ensemble member)\n    "\
    "    6. py__init_obs_pdaf\n    " \
    "       (if global adaptive forgetting factor\n    " \
    "       `type_forget=1` is used\n    " \
    "       in :func:`pyPDAF.PDAF.init`)\n    "\
    "    7. py__init_obsvar_pdaf (if global adaptive\n    " \
    "       forgetting factor is used)\n    "\
    "    8. loop over each local domain:\n    " \
    "        1. py__init_dim_l_pdaf\n    "\
    "        2. py__init_dim_obs_l_pdaf\n    "\
    "        3. py__g2l_state_pdaf\n    "\
    "        4. py__g2l_obs_pdaf (localise mean ensemble\n    " \
    "           in observation space)\n    "\
    "        5. py__init_obs_l_pdaf\n    " \
    "        6. py__g2l_obs_pdaf\n    "\
    "           (localise each ensemble member\n    " \
    "           in observation space)\n    "\
    "        7. py__init_obsvar_l_pdaf\n    " \
    "           (only called if local adaptive\n    " \
    "           forgetting factor `type_forget=2` is used)\n    " \
    "        8. py__prodRinvA_l_pdaf\n    "\
    "        9. core DA algorithm\n    " \
    "        10. py__l2g_state_pdaf\n    "\
    "    9. py__prepoststep_state_pdaf\n    "\
    "    10. py__distribute_state_pdaf\n    "\
    "    11. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.localomi_assimilate`\n    " \
    "   and :func:`pyPDAF.PDAF.localomi_assimilate_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Nerger, L., Janjić, T., Schröter, J., Hiller, W. (2012)." \
    "\n    " \
    "       A unification of ensemble square root Kalman filters." \
    "\n    " \
    "       Monthly Weather Review, 140, 2335-2345.\n    " \
    "       doi:10.1175/MWR-D-11-00102.1"
docstrings['assimilate_letkf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.localomi_assimilate`\n    "\
    "or :func:`pyPDAF.PDAF.localomi_assimilate_nondiagR`.\n\n    "\
    "PDAFlocal-OMI modules require fewer user-supplied\n    " \
    "functions and improved efficiency.\n\n    " \
    "Local ensemble transform Kalman filter (LETKF) [1]_ " \
    "for a single DA step without OMI.\n    " \
    "Implementation is based on [2]_.\n    " \
    "Note that the LESTKF is a more efficient equivalent\n    " \
    "to the LETKF.\n\n    " \
    "This function should be called at each model time step.\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_letkf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    "\
    "    2. py__prepoststep_state_pdaf\n    "\
    "    3. py__init_n_domains_p_pdaf\n    "\
    "    4. py__init_dim_obs_pdaf\n    "\
    "    5. py__obs_op_pdaf (for each ensemble member)\n    "\
    "    6. py__init_obs_pdaf\n    " \
    "       (if global adaptive forgetting factor\n    " \
    "       `type_forget=1` is used\n    " \
    "       in :func:`pyPDAF.PDAF.init`)\n    "\
    "    7. py__init_obsvar_pdaf (if global adaptive\n    " \
    "       forgetting factor is used)\n    "\
    "    8. loop over each local domain:\n    " \
    "        1. py__init_dim_l_pdaf\n    "\
    "        2. py__init_dim_obs_l_pdaf\n    "\
    "        3. py__g2l_state_pdaf\n    "\
    "        4. py__g2l_obs_pdaf (localise mean ensemble\n    " \
    "           in observation space)\n    "\
    "        5. py__init_obs_l_pdaf\n    " \
    "        6. py__g2l_obs_pdaf (localise each ensemble member" \
    "\n    " \
    "           in observation space)\n    "\
    "        7. py__init_obsvar_l_pdaf\n    " \
    "           (only called if local adaptive forgetting factor" \
    "\n    " \
    "           `type_forget=2` is used)\n    " \
    "        8. py__prodRinvA_l_pdaf\n    "\
    "        9. core DA algorithm\n    " \
    "        10. py__l2g_state_pdaf\n    "\
    "    9. py__prepoststep_state_pdaf\n    "\
    "    10. py__distribute_state_pdaf\n    "\
    "    11. py__next_observation_pdaf\n\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.localomi_assimilate`\n    " \
    "   and :func:`pyPDAF.PDAF.localomi_assimilate_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Hunt, B. R., Kostelich, E. J., & Szunyogh, I. (2007)." \
    "\n    "\
    "       Efficient data assimilation for spatiotemporal chaos:" \
    "\n    "\
    "       A local ensemble transform Kalman filter. \n    " \
    "       Physica D: Nonlinear Phenomena, 230(1-2), 112-126." \
    "\n    " \
    ".. [2] Nerger, L., Janjić, T., Schröter, J., Hiller, W. (2012)." \
    "\n    " \
    "       A unification of ensemble square root Kalman filters." \
    "\n    " \
    "       Monthly Weather Review, 140, 2335-2345.\n    " \
    "       doi:10.1175/MWR-D-11-00102.1"
docstrings['assimilate_lseik'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.localomi_assimilate`\n    "\
    "or :func:`pyPDAF.PDAF.localomi_assimilate_nondiagR`.\n\n    "\
    "PDAF-OMI modules require fewer user-supplied\n    " \
    "functions and improved efficiency.\n\n    " \
    "Local singular evolutive interpolated Kalman filter [1]_\n    " \
    "for a single DA step.\n    " \
    "This function should be called at each model time step.\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_lseik` " \
    "and :func:`pyPDAF.PDAF.get_state`\n\n    "\
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_n_domains_p_pdaf\n    " \
    "    4. py__init_dim_obs_pdaf\n    " \
    "    5. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    6. py__init_obs_pdaf\n    "\
    "       (if global adaptive forgetting factor `type_forget=1`" \
    "\n    " \
    "       is used in :func:`pyPDAF.PDAF.init`)\n    " \
    "    7. py__init_obsvar_pdaf\n    "\
    "       (if global adaptive forgetting factor is used)\n    " \
    "    8. loop over each local domain:\n    " \
    "        1. py__init_dim_l_pdaf\n    " \
    "        2. py__init_dim_obs_l_pdaf\n    " \
    "        3. py__g2l_state_pdaf\n    " \
    "        4. py__g2l_obs_pdaf (localise mean ensemble\n    " \
    "           in observation space)\n    " \
    "        5. py__init_obs_l_pdaf\n    "\
    "        6. py__g2l_obs_pdaf\n    "\
    "           (localise each ensemble member in observation space)" \
    "\n    " \
    "        7. py__init_obsvar_l_pdaf\n    "\
    "           (only called if local adaptive forgetting\n    " \
    "           factor `type_forget=2` is used)\n    "\
    "        8. py__prodRinvA_l_pdaf\n    " \
    "        9. core DA algorithm\n    " \
    "        10. py__l2g_state_pdaf\n    " \
    "    9. py__prepoststep_state_pdaf\n    " \
    "    10. py__distribute_state_pdaf\n    " \
    "    11. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.localomi_assimilate`\n    " \
    "   and :func:`pyPDAF.PDAF.localomi_assimilate_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Pham, D. T., Verron, J., & Roubaud, M. C. (1998).\n    " \
    "       A singular evolutive extended Kalman filter\n    " \
    "       for data assimilation\n    "\
    "       in oceanography. Journal of Marine systems,\n    " \
    "       16(3-4), 323-340."
docstrings['assimilate_lnetf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.localomi_assimilate`\n    "\
    "or :func:`pyPDAF.PDAF.localomi_assimilate_lnetf_nondiagR`.\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "Local Nonlinear Ensemble Transform Filter (LNETF) [1]_\n    " \
    "for a single DA step.\n    " \
    "The nonlinear filter computes the distribution up to\n    " \
    "the second moment similar to Kalman filters but\n    " \
    "it uses a nonlinear weighting similar to\n    " \
    "particle filters. This leads to an equal weights assumption\n    " \
    "for the prior ensemble at each step.\n    " \
    "This function should be called at each model time step.\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_lnetf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_n_domains_p_pdaf\n    " \
    "    4. py__init_dim_obs_pdaf\n    " \
    "    5. py__obs_op_pdaf (for each ensemble member)\n    " \
    "    6. loop over each local domain:\n    " \
    "        1. py__init_dim_l_pdaf\n    " \
    "        2. py__init_dim_obs_l_pdaf\n    " \
    "        3. py__g2l_state_pdaf\n    " \
    "        4. py__init_obs_l_pdaf\n    "\
    "        5. py__g2l_obs_pdaf (localise each ensemble\n    " \
    "           member in observation space)\n    " \
    "        6. py__likelihood_l_pdaf\n    " \
    "        7. core DA algorithm\n    " \
    "        8. py__l2g_state_pdaf\n    " \
    "    7. py__prepoststep_state_pdaf\n    " \
    "    8. py__distribute_state_pdaf\n    " \
    "    9. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.localomi_assimilate`\n    " \
    "   and :func:`pyPDAF.PDAF.localomi_assimilate_lnetf_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Tödter, J., and B. Ahrens, 2015:\n    "\
    "       A second-order exact ensemble square root filter\n    " \
    "       for nonlinear data assimilation. Mon. Wea. Rev.,\n    " \
    "       143, 1347–1367, doi:10.1175/MWR-D-14-00108.1."
docstrings['assimilate_lknetf'] = \
    "It is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.localomi_assimilate`\n    "\
    "or :func:`pyPDAF.PDAF.localomi_assimilate_lknetf_nondiagR`." \
    "\n\n    "\
    "PDAF-OMI modules require fewer user-supplied functions\n    " \
    "and improved efficiency.\n\n    " \
    "A hybridised LETKF and LNETF [1]_ for a single DA step.\n    " \
    "The LNETF computes the distribution up to\n    " \
    "the second moment similar to Kalman filters but\n    " \
    "using a nonlinear weighting similar to\n    " \
    "particle filters. This leads to an equal weights\n    " \
    "assumption for the prior ensemble.\n    " \
    "The hybridisation with LETKF is expected to lead to\n    " \
    "improved performance for quasi-Gaussian problems.\n    " \
    "The function should be called at each model step.\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_lknetf`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    " \
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_n_domains_p_pdaf\n    " \
    "    4. py__init_dim_obs_pdaf\n    " \
    "    5. py__obs_op_pdaf\n    "\
    "       (for each ensemble member)\n    " \
    "    6. py__init_obs_pdaf\n    " \
    "       (if global adaptive forgetting factor `type_forget=1`" \
    "\n    "\
    "       is used in :func:`pyPDAF.PDAF.init`)\n    " \
    "    7. py__init_obsvar_pdaf (if global adaptive\n    " \
    "       forgetting factor is used)\n    " \
    "    8. loop over each local domain:\n    " \
    "        1. py__init_dim_l_pdaf\n    " \
    "        2. py__init_dim_obs_l_pdaf\n    " \
    "        3. py__g2l_state_pdaf\n    " \
    "        4. py__g2l_obs_pdaf\n    "\
    "           (localise each ensemble member\n    " \
    "           in observation space)\n    " \
    "        5. py__init_obs_l_pdaf\n    "\
    "        6. py__init_obsvar_l_pdaf\n    "\
    "           (only called if local adaptive forgetting\n    " \
    "           factor `type_forget=2` is used)\n    "\
    "        7. py__prodRinvA_pdaf\n    " \
    "        8. py__likelihood_l_pdaf\n    " \
    "        9. core DA algorithm\n    " \
    "        10. py__l2g_state_pdaf\n    " \
    "    9. py__obs_op_pdaf\n    " \
    "       (only called with `HKN` and `HNK` options\n    " \
    "       called for each ensemble member)\n    " \
    "    10. py__likelihood_hyb_l_pda\n    " \
    "    11. py__init_obsvar_l_pdaf\n    " \
    "        (only called if local adaptive forgetting\n    " \
    "        factor `type_forget=2` is used)\n    "\
    "    12. py__prodRinvA_hyb_l_pdaf\n    " \
    "    13. py__prepoststep_state_pdaf\n    " \
    "    14. py__distribute_state_pdaf\n    " \
    "    15. py__next_observation_pdaf\n" \
    "\n    " \
    ".. deprecated:: 1.0.0\n\n    " \
    "   This function is replaced by\n    " \
    "   :func:`pyPDAF.PDAF.localomi_assimilate`\n    " \
    "   and :func:`pyPDAF.PDAF.localomi_assimilate_lknetf_nondiagR`" \
    "\n\n    " \
    "References\n    " \
    "----------\n    " \
    ".. [1] Nerger, L.. (2022) \n    " \
    "       Data assimilation for nonlinear systems with\n    " \
    "       a hybrid nonlinear Kalman ensemble transform filter." \
    "\n    " \
    "       Q J R Meteorol Soc, 620–640. doi:10.1002/qj.4221"
docstrings['assimilate_prepost'] = \
    "It is used to preprocess and postprocess of the ensemble." \
    "\n\n    " \
    "No DA is performed in this function.\n    " \
    "Compared to :func:`pyPDAF.PDAF.prepost`,\n    " \
    "this function sets assimilation flag, \n    " \
    "which means that it is acted as an assimilation in PDAF." \
    "\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_prepost`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    "\
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf (preprocess, step < 0)\n    " \
    "    3. py__prepoststep_state_pdaf (postprocess, step > 0)\n    " \
    "    4. py__distribute_state_pdaf\n    " \
    "    5. py__next_observation_pdaf"
docstrings['generate_obs'] = \
    "Generation of synthetic observations based on\n    " \
    "given error statistics and observation operator.\n\n    " \
    "When diagonal observation error covariance matrix is used,\n    " \
    "it is recommended to use\n    " \
    ":func:`pyPDAF.PDAF.omi_generate_obs` functionalities\n    "\
    "for fewer user-supplied functions and improved efficiency.\n\n    " \
    "The generated synthetic observations are based on\n    " \
    "each member of model forecast.\n    " \
    "Therefore, an ensemble of observations can be obtained.\n    " \
    "In a typical experiment,\n    "\
    "one may only need one ensemble member.\n    " \
    "The implementation strategy is similar to\n    " \
    "an assimilation step. This means that, \n    " \
    "one can reuse many user-supplied functions for\n    " \
    "assimilation and observation generation.\n\n    " \
    "The function is a combination of\n    " \
    ":func:`pyPDAF.PDAF.put_state_generate_obs`\n    " \
    "and :func:`pyPDAF.PDAF.get_state`.\n\n    "\
    "User-supplied functions are executed in the following sequence:\n    " \
    "    1. py__collect_state_pdaf\n    " \
    "    2. py__prepoststep_state_pdaf\n    " \
    "    3. py__init_dim_obs_pdaf\n    " \
    "    4. py__obs_op_pda\n    " \
    "    5. py__init_obserr_f_pdaf\n    " \
    "    6. py__get_obs_f_pdaf\n    " \
    "    7. py__prepoststep_state_pdaf\n    " \
    "    8. py__distribute_state_pdaf\n    " \
    "    9. py__next_observation_pdaf"
