{% set version = "1.0.4" %}

package:
  name: pypdaf
  version: {{ version }}

source:
  path: ..

build:
  number: 0

requirements:
  host:
    - python
    - meson-python {{ pymeson }}
    - numpy {{numpy_version}}
    - {{ mpi }}
    - mpi4py
    - openblas
    - flang-rt_win-64 # [win]
    - libflang # [win]
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - vs2022_win-64     # [win]
    - numpy {{numpy_version}}
    - cython
  run:
    - flang-rt_win-64 # [win]
    - python
    - numpy
    - {{ mpi }}
    - mpi4py
    - openblas

pin_run_as_build:
    {{ mpi }}: x.x
    mpi4py: x.x
    openblas: x.x

about:
  home: https://github.com/yumengch/pyPDAF
  summary: A Python interface to PDAF
  description: pyPDAF is a python interface to the Fortran-based PDAF library
  license: GPL
  doc_url: https://yumengch.github.io/pyPDAF/index.html
  dev_url: https://github.com/yumengch/pyPDAF