{% set version = "1.1" %}

package:
  name: pypdaf
  version: {{ version }}

source:
  path: ..

build:
  number: {{ 2 if openmp == "false" and freethreaded == "false" else 0 }}
  string: py{{ CONDA_PY }}{% if freethreaded == "true" %}t{% endif %}{% if openmp == "true" %}_openmp{% endif %}_{{ PKG_BUILDNUM }}
  skip: true  # [py<314 and freethreaded]

requirements:
  host:
    - python
    - python-freethreading # [freethreaded]
    - meson-python {{ pymeson }}
    - numpy
    - mpi=*={{ mpi }}
    - mpi4py
    - blas=*=openblas
    - flang-rt_win-64 # [win]
    - libflang # [win]
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - libgomp      # [linux and openmp]
    - llvm-openmp  # [osx and openmp]    
    - llvm-openmp-fortran  # [win and openmp]
    - vs2022_win-64     # [win]
    - numpy
    - cython
  run:
    - flang-rt_win-64 # [win]
    - python
    - python-freethreading # [freethreaded]
    - numpy>2
    - mpi=*={{ mpi }}
    - mpi4py
    - blas=*=openblas
    - {{ pin_compatible('libgomp', exact=True) }} # [linux and openmp]
    - {{ pin_compatible('llvm-openmp', exact=True) }} # [osx and openmp]
    - {{ pin_compatible('llvm-openmp-fortran', exact=True) }} # [win and openmp]

pin_run_as_build:
    mpi: x.x
    mpi4py: x.x
    blas: x.x

about:
  home: https://github.com/yumengch/pyPDAF
  summary: A Python interface to PDAF
  description: pyPDAF is a python interface to the Fortran-based PDAF library
  license: GPL
  doc_url: https://yumengch.github.io/pyPDAF/index.html
  dev_url: https://github.com/yumengch/pyPDAF
