{% set version = "0.03" %}

package:
  name: pypdaf
  version: 0.0.3

source:
  noarch: python
  path: ..

build:
  preserve_egg_dir: True

requirements:
  host:
    - python {{python}}
    - setuptools
    - pip
    - cython
    - numpy
    - mpi4py
    - {{ mpi }}
    - mkl-static                 # [not osx]
    - blas-devel=*=*netlib*      # [osx]
    - liblapack=*=*netlib*       # [osx]
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [not win]
    - cmake   # [not win]
    - make    # [not win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - mpi4py
    - intel-fortran-rt=2024.2.0 # [win]
    - {{ mpi }}
    - blas-devel=*=*netlib* # [osx]
    - liblapack=*=*netlib* # [osx]

about:
  home: https://github.com/yumengch/pyPDAF
  summary: A Python interface to PDAF
  description: |
    pyPDAF is a python interface to the Fortran-based PDAF library
  license: GPL
  doc_url: https://yumengch.github.io/pyPDAF/index.html
  dev_url: https://github.com/yumengch/pyPDAF