name: conda_build_mac_intel
on: [workflow_dispatch]
jobs:
  upload_conda_mac_intel:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: upgrade2.2.1

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          auto-update-conda: true
          activate-environment: ""

      - name: build pyPDAF
        shell: bash -el {0}
        run: |
          cp PDAFBuild/setup_conda_intel_mac.cfg setup.cfg
          conda install python anaconda-client conda-build conda-verify
          anaconda login --username yumengch --password ${{ secrets.ANACONDA }}
          conda  config --set anaconda_upload yes
          conda-build -c conda-forge conda.recipe/

      - name: install pyPDAF
        shell: bash -el {0}
        run: |
          conda install -y -c conda-forge --use-local pypdaf
          mv example/config_mac.py example/config.py
          mv example/config_obsA_mac.py example/config_obsA.py
          mpiexec -n 4 python -u example/main.py 

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3