name: test_mac_build
on: [workflow_dispatch]

jobs:
  test_mac_build:
    runs-on: macos-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: upgrade2.2.1
      
      - name: Setup Fortran compiler
        uses: fortran-lang/setup-fortran@v1.6.1
        id: setup-fortran
        with:
          compiler: gcc
          version: 13

      - name: install dependent Libaries
        run: brew install openblas lapack open-mpi

      - name: Set up Python 3.x
        uses: actions/setup-python@v5

      - name: install pyPDAF
        run: |
          mv setup_mac.cfg setup.cfg
          pip install -v .

      - name: run example
        run: |
          mv example/config_mac.py example/config.py
          mv example/config_obsA_mac.py example/config_obsA.py
          mpiexec --oversubscribe -n 4 python -u example/main.py

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3